import {
    eventPhoto1,
    eventPhoto2,
    eventPhoto3,
    eventPhoto4,
    eventPhoto5,
    eventPhoto6,
    eventPhoto7,
    eventPhoto8,
    eventPhoto9,
    eventPhoto10,
    eventPhoto11,
    eventPhoto12,
    eventPhoto13,
    eventPhoto14,
    eventPhoto15,
    eventPhoto16,
    eventPhoto17,
    eventPhoto18,
    eventPhoto19,
    eventPhoto20,
    eventPhoto21,
    eventPhoto22,
    eventPhoto23,
    eventPhoto24,
    eventPhoto25,
} from "../../assets";

export interface GalleryImage {
    id: string;
    src: string;
    alt: string;
    title?: string;      // optional
    description?: string; // optional
}

export const galleryImages: GalleryImage[] = [
    {
        id: "1",
        src: eventPhoto1,
        alt: "TEDx Event Image 1",
        // title: "رویداد شماره یک",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "2",
        src: eventPhoto2,
        alt: "TEDx Event Image 2",
        // title: "رویداد شماره دو",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "3",
        src: eventPhoto3,
        alt: "TEDx Event Image 3",
        // title: "رویداد شماره سه",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "4",
        src: eventPhoto4,
        alt: "TEDx Event Image 4",
        // title: "رویداد شماره چهار",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "5",
        src: eventPhoto5,
        alt: "TEDx Event Image 5",
        // title: "رویداد شماره پنج",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "6",
        src: eventPhoto6,
        alt: "TEDx Event Image 6",
        // title: "رویداد شماره شش",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "7",
        src: eventPhoto7,
        alt: "TEDx Event Image 7",
        // title: "رویداد شماره هفت",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "8",
        src: eventPhoto8,
        alt: "TEDx Event Image 8",
        // title: "رویداد شماره هشت",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "9",
        src: eventPhoto9,
        alt: "TEDx Event Image 9",
        // title: "رویداد شماره نه",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "10",
        src: eventPhoto10,
        alt: "TEDx Event Image 10",
        // title: "رویداد شماره ده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "11",
        src: eventPhoto11,
        alt: "TEDx Event Image 11",
        // title: "رویداد شماره یازده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "12",
        src: eventPhoto12,
        alt: "TEDx Event Image 12",
        // title: "رویداد شماره دوازده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "13",
        src: eventPhoto13,
        alt: "TEDx Event Image 13",
        // title: "رویداد شماره سیزده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "14",
        src: eventPhoto14,
        alt: "TEDx Event Image 14",
        // title: "رویداد شماره چهارده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "15",
        src: eventPhoto15,
        alt: "TEDx Event Image 15",
        // title: "رویداد شماره پانزده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "16",
        src: eventPhoto16,
        alt: "TEDx Event Image 16",
        // title: "رویداد شماره شانزده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "17",
        src: eventPhoto17,
        alt: "TEDx Event Image 17",
        // title: "رویداد شماره هفده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "18",
        src: eventPhoto18,
        alt: "TEDx Event Image 18",
        // title: "رویداد شماره هجده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "19",
        src: eventPhoto19,
        alt: "TEDx Event Image 19",
        // title: "رویداد شماره نوزده",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "20",
        src: eventPhoto20,
        alt: "TEDx Event Image 20",
        // title: "رویداد شماره بیست",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "21",
        src: eventPhoto21,
        alt: "TEDx Event Image 21",
        // title: "رویداد شماره بیست و یک",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "22",
        src: eventPhoto22,
        alt: "TEDx Event Image 22",
        // title: "رویداد شماره بیست و دو",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "23",
        src: eventPhoto23,
        alt: "TEDx Event Image 23",
        // title: "رویداد شماره بیست و سه",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "24",
        src: eventPhoto24,
        alt: "TEDx Event Image 24",
        // title: "رویداد شماره بیست و چهار",
        // description: "رویداد تداِکس امیرکبیر",
    },
    {
        id: "25",
        src: eventPhoto25,
        alt: "TEDx Event Image 25",
        // title: "رویداد شماره بیست و پنج",
        // description: "رویداد تداِکس امیرکبیر",
    },
];
